apiVersion: v1
kind: Pod
metadata:
  name: twopod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    resources:
      requests:
        memory: "100Mi"
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]

  - name: redis
    image: redis
    ports:
    - containerPort: 6379
    resources:
      limits:
        memory: "100Mi"
