apiVersion: v1
kind: Pod
metadata:
  name: zcpod
  namespace: test
  labels:
    app: novnc
spec:
  containers:
    - name: zccontainer
      image: zhangcheng0111/ubuntu-untiy-novnc
      env:
        - name: PASSWORD
          value: '123'
        - name: SUDO
          value: 'yes'
      ports:
      - containerPort: 22
      - containerPort: 6080
---
apiVersion: v1
kind: Service
metadata:
  name: zc-pod004-svc
  namespace: test
spec:
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  - name: vnc
    port: 6080
    targetPort: 6080
  selector:
    app: novnc
  type: NodePort