apiVersion: v1
kind: Pod
metaname:
  name: busy-httpd
spec:
  container:
    - name: busy
      image: busybox
      command: ['while True; do sleep(30); done']        
    resource:
    ports:
      - containerport: 80
