apiVersion: v1
kind: Pod
metadata:
  name: configmaptest
  labels:
    app: novnc
spec:
  containers:
    - name: configmaptest
      image: ubuntu
      command: ['/bin/bash','-c']
      args: [--','while true; do sleep(20);done;']
      env:
      - name: configmap
        valueFrom:
          configMapKeyRef: 
            name: test
            key: name