apiVersion: v1
kind: Pod
metadata:
  name: davidnotebook
  labels:
    app: jupyter-notebook
spec:
  containers:
    - name: notebook
      image: 40660367/myub18_notebook
      imagePullPolicy: IfNotPresent
      command: ['jupyter']
      args: ['notebook','~','--allow-root','--ip=0.0.0.0']
      ports:
        - containerPort: 8080
      workingDir: '~'
      volumeMounts:
        - name: githubRepo
          readOnly: True
          mountPath: ~/shareData
      resources:
        requests:
          cpu: 100m
          memory: 500Mi
        limits:
          cpu: 300m
          memroy: 800Mi
  volumes:
    - name: githubRepo
      gitRepo:
        repository: https://github.com/40660367/tensorflow_tutorials.git
---
apiVersion: v1
kind: Service
metadata:
  name: davidnotebookservice
  labels:
    app: jupyter-notebook
spec:
  type: NodePort
  selector:
    app: jupyter-notebook
  port: 8080
