apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
  namespace: default
  labels:
    app: stress
spec:
  containers:
    - name: stress-container
      image: ikubernetes/stress-ng
      command: ['/usr/bin/stress-ng']
      args: ['--cpu 1','--metrics-brief']
      resources:
        requests:
          cpu: 300m
          memory: 100Mi
        limits:
          cpu: 500m
          memory: 300Mi
          
