kind: PersistentVolume
apiVersion: v1
metadata:
  name: tornado-mnt-nas-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tornado-mnt-nas-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tornado
spec:
  selector:
    matchLabels:
      app: tornado-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tornado-server
    spec:
      serviceAccountName: system:admin
      containers:
      - image: ccr.ccs.tencentyun.com/david/tornado:v8
        name: tornado-server-container
        env:
          # Use secret in real usage
        - name: MYSQL_PASSWORD
          value: password
        volumeMounts:
        - name: tornado-mnt-nas-volume
          mountPath: /mnt
        resources: 
          limits:
            cpu: 500m
            memory: 500Mi
    volumes:
    - name: tornado-mnt-nas-volume
     persistentVolumeClaim: 
       claimName: tornado-mnt-nas-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: "tornado"
  labels:
    app: tornado
spec:
  type: Node
  selector:
    run: tornado-server
  ports:
    - port: 80
      targetPort: 9100
