kind: PersistentVolume
apiVersion: v1
metadata:
  name: tornado-mnt-nas-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tornado-mnt-nas-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: tornado-server
  name: tornado
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tornado  
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
    spec:
      containers:
      - image: ccr.ccs.tencentyun.com/david/tornado:v8
        imagePullPolicy: IfNotPresent
        name: tornado
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: tornado-mnt-nas-volume
          mountPath: /mnt
        resources: 
          limits:
            cpu: 500m
            memory: 500Mi
      volumes:
      - name: tornado-mnt-nas-volume
        persistentVolumeClaim:
          claimName: tornado-mnt-nas-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: "tornado"
  labels:
    app: tornado
spec:
  type: NodePort
  selector:
    run: tornado-server
  ports:
    - port: 80
      targetPort: 9100
