apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      requests:
        cpu:
          100m
        memory:
          50Mi
      limits:
        cpu:
          200m
        memory:
          80Mi
