kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pod/ubuntu-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  volumes:
    - name: pvc1
      persistentVolumeClaim: 
        claimName: ubuntu-pv-claim
     - name: git1
       gitRepo:
         repository: https://github.com/40660367/YAML.git
  containers:
  - image: ubuntu
    name: ubuntu
    volumeMounts:
      - name: pvc1
        mountPath: /mnt/data
      - name: git1
        mountPath: /mnt/github
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      requests:
        cpu:
          100m
        memory:
          50Mi
      limits:
        cpu:
          200m
        memory:
          80Mi
    
