apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  volumes:
  - name: cache-volume
    emptyDir: {}
